server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: playlist
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/playlist/**
          filters:
            - AuthFilter
        - id: users
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter
        - id: songs
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

SECRET_KEY: "6ed1eb0150e8f8fb285ec976ce500807406933985fbea5086c690eb221e53f5a"
