server:
  port: 9090

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/cowradio
    username: postgres
    password: Borman15
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY: "6ed1eb0150e8f8fb285ec976ce500807406933985fbea5086c690eb221e53f5a"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG

