server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888 #Configuracion


eureka:
  instance:
    hostname: localhost #Servidor en donde funcionara
  client:
    register-with-eureka: false #Indicamos que no se registre a si mismo
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka


