server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: playlist
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/playlist**
        - id: users
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter
        - id: songs
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka